### ISSUE TITLE
扫码确认后报错

### ISSUE THREAD

**Issue by l-we** [ehForwarderBot/efb-wechat-slave#119]
```
2021-10-26 12:53:28,972 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:193)
    Confirm on your phone.
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.7/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/__init__.py", line 158, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/__init__.py", line 672, in authenticate
    start_immediately=not first_start)
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 88, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/vendor/itchat/components/register.py", line 33, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 56, in login
    status = self.check_login()
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 148, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 193, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by blueset** [comment]
网页版 wc 可以用浏览器正常使用吗？

**Comment by l-we** [comment]
也不能用，但是过断时间又会恢复能登录，
在发生这个问题之前会报一个消息太多错误，会不会是新的验证机制
下次在发生我把之前的错误发出来，现在看不到了

**Comment by blueset** [comment]
Closing due to inactivity
