### ISSUE TITLE
[BUG] v2.0.7登录失败

### ISSUE THREAD

**Issue by joyoner** [ehForwarderBot/efb-wechat-slave#130]
### 版本信息 Version Info

EH Forwarder Bot
Version: 2.1.1
Python version:
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.2.4 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.7 # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述 Describe the bug

无法登录
扫描二维码-手机确认-日志失败
server refused, loading login status failed.

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
请在下方贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。

【贴在下面】
2022-01-17 14:43:50,050 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
    Confirm on your phone.
2022-01-17 14:43:57,449 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:198)
    Successfully logged in.
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/__init__.py", line 160, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/__init__.py", line 672, in authenticate
    self.bot: wxpy.Bot = wxpy.Bot(cache_path=str(efb_utils.get_data_path(self.channel_id) / "wxpy.pkl"),
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 85, in __init__
    self.core.auto_login(
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/register.py", line 32, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 80, in login
    self.verify_login()
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 106, in verify_login
    raise Exception('server refused, loading login status failed.')
Exception: server refused, loading login status failed.


【贴在上面】

```
 
</details>

**Comment by joyoner** [comment]
已解决，由于是升级的，删除历史配置重启就可以了。
~/.ehforwarderbot/profiles/default/blueset.wechat/
