### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Neo-peng** [ehForwarderBot/efb-wechat-slave#131]
### 版本信息 Version Info

```
EH Forwarder Bot
Version: 2.1.1
Python version:
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.2.4 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.7 # Default instance

Middlewares:
    No middleware is enabled.
```

### 问题描述 Describe the bug
今天提示可能session到期，然后重新扫码登陆微信失败

### 重现步骤 To Reproduce
重新扫码登陆微信

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
If the QR code was not shown correctly, please visit:
https://login.weixin.qq.com/qrcode/IbKzUQZGyQ==
2022-01-28 19:10:59,268 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
    Confirm on your phone.
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/__init__.py", line 160, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/__init__.py", line 672, in authenticate
    self.bot: wxpy.Bot = wxpy.Bot(cache_path=str(efb_utils.get_data_path(self.channel_id) / "wxpy.pkl"),
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 85, in __init__
    self.core.auto_login(
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/register.py", line 32, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 58, in login
    status = self.check_login()
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 171, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.9/dist-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 211, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 63, column 4

```
 
</details>

**Comment by yjyao** [comment]
i'm having this issue as well. why is this closed?

**Comment by Neo-peng** [comment]
I tried to login to the web version of Wechat, and it alert "login failed". So I guess that is why it show this error, this should be blamed to Wechat not this bot, so I closed this issue. @yjyao
