### ISSUE TITLE
[BUG] 这个报错会导致消息收不到么

### ISSUE THREAD

**Issue by FlechazoPh** [ehForwarderBot/efb-wechat-slave#135]
![image](https://user-images.githubusercontent.com/94276146/171194295-7acf51c0-0173-49d2-b134-824f4e612131.png)

```

May 31 22:01:05 oracle-centos-2 ehforwarderbot[3166]: r = adapter.send(request, **kwargs)
May 31 22:01:05 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
May 31 22:01:05 oracle-centos-2 ehforwarderbot[3166]: raise ConnectionError(err, request=request)
May 31 22:01:05 oracle-centos-2 ehforwarderbot[3166]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: 2022-05-31 22:04:35,060 [ERROR]: itchat (login.maintain_loop; login.py:325)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: Traceback (most recent call last):
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: chunked=chunked,
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 449, in _make_request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: six.raise_from(e, None)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "<string>", line 3, in raise_from
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 444, in _make_request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: httplib_response = conn.getresponse()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: response.begin()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 307, in begin
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: version, status, reason = self._read_status()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: raise RemoteDisconnected("Remote end closed connection without"
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: http.client.RemoteDisconnected: Remote end closed connection without response
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: During handling of the above exception, another exception occurred:
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: Traceback (most recent call last):
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: timeout=timeout
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: raise six.reraise(type(error), error, _stacktrace)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: raise value.with_traceback(tb)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: chunked=chunked,
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 449, in _make_request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: six.raise_from(e, None)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "<string>", line 3, in raise_from
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 444, in _make_request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: httplib_response = conn.getresponse()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: response.begin()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 307, in begin
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: version, status, reason = self._read_status()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: raise RemoteDisconnected("Remote end closed connection without"
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: During handling of the above exception, another exception occurred:
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: Traceback (most recent call last):
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 304, in maintain_loop
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: msgList, contactList = self.get_msg()
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 389, in get_msg
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: r = self.s.post(url, data=json.dumps(data), headers=headers, timeout=config.TIMEOUT)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 577, in post
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: return self.request('POST', url, data=data, json=json, **kwargs)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/misc.py", line 350, in customized_request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: return requests.Session.request(session, method, url, **kwargs)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: resp = self.send(prep, **send_kwargs)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: r = adapter.send(request, **kwargs)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: raise ConnectionError(err, request=request)
May 31 22:04:35 oracle-centos-2 ehforwarderbot[3166]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```

**Comment by blueset** [comment]
从日志上可以看出是服务器到 Web WC 的网络通讯不通畅造成的。

**Comment by FlechazoPh** [comment]
这个问题无法解决么，偶尔会有一些消息收不到

**Comment by mgcyung** [comment]
相同的问题，会导致ehforwarderbot异常退出

**Comment by FlechazoPh** [comment]
最近基本上三四天就会自动退出，需要重新扫码登录，用的iPad扫码登录的
